---
title: "more_dataset"
output: github_document
params:
  rds_path: "data/processed/tm_marrow.rds"
  description: "mouse_marrow"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mouse database

```{r, message=FALSE}
#loading packages
library(ggplot2)
library(ggbeeswarm)
library(zellkonverter)
library(dplyr)
library(SingleCellExperiment)
library(scRNAseq)
library(scater)
library(scran)
```

## Bone marrow data
```{r}
sce=readRDS(params$rds_path) #define parameter variable instead of original file path
colnames(sce)=sce$ori_cell_id
sce
View(as.data.frame(colData(sce)))

#create a smaller sample dataset 
set.seed(50590) 
sce_sub=sce[, sample(ncol(sce), .03* ncol(sce), replace = FALSE)] 
sce_sub

hm_sub=hm_sce[, sample(ncol(hm_sce), .03* ncol(hm_sce), replace = FALSE)] 
hm_sub
```

## Functions
```{r}
source('PCA.r')
source('utility.R')
n_folds = 20

# Uniformly random sampling test set
uniform_random_test=function(sce, n_folds){
  train_idx <- sample(ncol(sce), .66* ncol(sce), replace = FALSE)  
  sce.bio_replicates<-unique(sce$bio_replicates) 
  cell_batch_df = as.data.frame(colData(sce), optional = TRUE) %>% 
    dplyr::select(bio_replicates, tissue, sex, age) %>% mutate(cell_idx = seq_along(sce$bio_replicates))
  batch_df = cell_batch_df %>% dplyr::select(tissue, bio_replicates) %>% unique() %>% arrange(tissue) %>% mutate(fold = rep_len(seq(from = 1, to = n_folds), length(bio_replicates)))
  cell_batch_df = left_join(cell_batch_df, batch_df, by = c('tissue', 'bio_replicates'))
  fold_train = sample(n_folds, size = floor(.66 * n_folds), replace = FALSE)
  cell_train = filter(cell_batch_df, fold %in% fold_train) %>% pull(cell_idx)
  result=list(cell_batch_df, fold_train, cell_train)
  return(result)
} 

uniform_random_test(sce = hm_sub, n_folds = n_folds)

# Cross-validation by batches
cross_validation_batch=function(sce, n_folds){
  cell_batch_df = uniform_random_test(sce, n_folds)[[1]]
  cell_train = uniform_random_test(sce, n_folds)[[3]]
  #stratified by batch
  test_batch = split_and_label(sce, cell_train, dimred_test = 'PCA')
  train_only = split_and_label(sce, seq_len(ncol(sce)), dimred_test = 'PCA')
  concordance_stats=concordance_stats(ref = train_only$train[, -cell_train], query=test_batch$test)
  return(concordance_stats)
}

cross_validation_batch(sce = hm_sub, n_folds = n_folds)

# Full cross-validation
#cell_batch_df = uniform_random_test(sce, n_folds)[[1]]
#rsem = vfold_resample(sce, fold_map = cell_batch_df, return_train = 'tbl', return_test = 'tbl')



# Permute fold labels, iterate over batches and plot the concordances
permute_ite_plot=function(sce, n_folds){
  cell_train = uniform_random_test(sce, n_folds)[[3]]
  train_only = split_and_label(sce, seq_len(ncol(sce)), dimred_test = 'PCA')
  #permute labels
  uni_folds = data.frame(fold = sample(cell_batch_df$fold), cell_idx = seq_along(sce$bio_replicates))
  uni_rsem = vfold_resample(sce, fold_map = uni_folds, train_args=NULL, return_train = 'tbl', return_test = 'tbl')
  
  #iterate over each batch as held-out data
  batch_fold_stat_train = purrr::map_dfr(uni_rsem, function(fold){
    x = fold$train
    st = concordance_stats(train_only$train[, as.character(x$ori_cell_id)], x)
    as_tibble(st[c('accuracy_rate', 'adj_RandIndex', 'test_nclust')])
  }, .id = 'fold')
  

  #plot concordance between resampled training data
  batch_fold_stat = purrr::map_dfr(rsem, function(fold){
    x = fold$test
    st = concordance_stats(train_only$train[, as.character(x$ori_cell_id)], x)
    as_tibble(st[c('accuracy_rate', 'adj_RandIndex', 'test_nclust')])
  }, .id = 'fold')
  
  uni_fold_stat =  purrr::map_dfr(uni_rsem, function(fold){
    x = fold$test
    st = concordance_stats(train_only$train[, as.character(x$ori_cell_id)], x)
    as_tibble(st[c('accuracy_rate', 'adj_RandIndex', 'test_nclust')])
  }, .id = 'fold')
  
  fold_stat = bind_rows(list(batch = batch_fold_stat, uniform = uni_fold_stat, stability = batch_fold_stat_train), .id = 'scheme') %>%
    mutate(scheme = factor(scheme, levels = c('batch', 'uniform', 'stability')))
  
  plt = ggplot(fold_stat, aes(x = scheme, y = adj_RandIndex)) + 
    geom_beeswarm() + 
    theme_minimal() + 
    stat_summary(color = 'red', lwd = .5) + xlab("Resampling Scheme")
  plot_adi=plt + ylab("Adjusted Rand Index") 
  plot_con=plt + aes(y = accuracy_rate) + ylab("Concordance")
  plot_cluster=plt + aes(y = test_nclust) + ylab("# of clusters")
  
  return(list(fold_stat, plt, plot_adi, plot_con, plot_cluster))
}


```


```{r}
uniform_random_test(sce = sce_sub, n_folds = n_folds)
cross_validation_batch(sce = sce_sub, n_folds = n_folds)
cell_batch_df = uniform_random_test(sce_sub, n_folds)[[1]]
rsem = vfold_resample(sce=sce_sub, fold_map = cell_batch_df, return_train = 'tbl', return_test = 'tbl')
permute_ite_plot(sce = sce_sub, n_folds = n_folds)

```


## Mouse Brain dataset
```{r}
sce_brain=readRDS('data/processed/tm_brain.rds')
sce_brain
colnames(sce_brain)=sce_brain$ori_cell_id

sce_brain

set.seed(50590) 
sce_brain_sub=sce[, sample(ncol(sce_brain), .03* ncol(sce_brain), replace = FALSE)] 
sce_brain_sub


uniform_random_test(sce = sce_brain_sub, n_folds = n_folds)
cross_validation_batch(sce = sce_brain_sub, n_folds = n_folds)
cell_batch_df = uniform_random_test(sce_brain_sub, n_folds)[[1]]
rsem = vfold_resample(sce=sce_brain_sub, fold_map = cell_batch_df, return_train = 'tbl', return_test = 'tbl')
permute_ite_plot(sce = sce_brain_sub, n_folds = n_folds)
```

```{r, UMAP-exp}
train_only = split_and_label(sce_sub, seq_len(ncol(sce_sub)), dimred_test = 'PCA')
train_only$train = runUMAP(train_only$train)
plotReducedDim(train_only$train, 'UMAP', colour_by = 'label') + ggtitle('By Label')

#plotReducedDim(train_only$train, 'UMAP', colour_by = 'batch') + theme(legend.pos = 'none') + ggtitle('By Batch')
```

#Human Lung Cell Dataset
```{r}
sce_lung=read.csv('Metadata_lung_cells.csv')
sce_lung
any(duplicated(sce_lung$X))
View(as.data.frame(sce_lung))
any(is.na(sce_lung))

unique(sce_lung$ID) #patient ID is the bio_replicate, X can be renamed as ori_cell_id
table(sce_lung$Sex)
table(sce_lung$Age)

csv_mat = readr::read_csv("Counts_lung_cells.csv")
metadata = readr::read_csv("path_to_metadata.csv")
#for assay names, keep everything expect gene names; 
sce = SingleCellExperiment(assay = list(counts = csv_mat[,-1]), colData = metadata[-1,], rowData = csv_mat[,1,drop = FALSE])
```


